# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 17:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='btw',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(b'^\\d{9}$', 'Gelieve een nummer van 9 cijfers in te voeren zonder het BEvoorvoegsel.')]),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(b'^\\+?1?\\d{9,15}$', "Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")]),
        ),
    ]
